# Generated by Django 4.2.6 on 2023-10-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('p_name', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.year')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('m_id', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.team')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.team')),
            ],
        ),
    ]
