# Generated by Django 4.1 on 2023-11-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='team_id',
            new_name='team',
        ),
    ]
