# Generated by Django 4.1 on 2023-11-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_rename_team_id_photo_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
